logging:
  level:
    org:
      springframework:
        security: DEBUG
    hibernate: DEBUG
    pattern: 
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
spring:
  datasource:
    password: 
    platform: H2
    url: jdbc:h2:mem:ems;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
h2:
    console:
      enabled: true
      path: /h2console
      settings:
        trace: false
        web-allow-others: false
management:
  endpoint:
    restart:
      enabled: true
    refresh:
      enabled: true
      
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:7777/eureka/
    healthcheck:
      enabled: true