spring:
  application:
    name: department-service
  profiles:
    active: development 
  datasource:
    password: root
    platform: POSTGRESQL
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
