server:
  port: 8081
spring:
  datasource:
    password: root
    platform: POSTGRESQL
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
    hibernate: DEBUG
    pattern: 
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"